server.port=8081

spring.profiles.active=railway


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false