server.port=8081

spring.profiles.active=railway

cloudinary.cloud_name=dz1jyfwrw
cloudinary.api_key=765759794817639
cloudinary.api_secret=ag1qUHBuZJCdko8BCGHzG-JOTmc
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false